### ISSUE TITLE
Update to Angular 12

### ISSUE THREAD

**Issue by GuilhermeRabelo** [Lowpoc/angular-validate-br#4]
![image](https://user-images.githubusercontent.com/43557775/129097293-40366484-a8d1-40c4-a809-bc4b28099cb6.png)

My project used to be on Angular version 8, then I've update to Angular 12 and i'm having some issues with the "until" on your lib, can you help me?

**Comment by MarcusSilvaDev** [comment]
Hello dear, well currently the library is deprecated.  I make this lib to deep learn about validation. If you may be interested we talk in discord about it and see other possibilities for you. 

Discord: Marcus(Lowpoc/_Titan)#9081
